### ISSUE TITLE
zsh completions

### ISSUE THREAD

**Issue by soonho-tri** [bazelbuild/homebrew-tap#1]
Could you add zsh completions in `bazelbuild/tap/bazel`? It was included in the `homebrew/core/bazel` but not anymore in `bazelbuild/tap/bazel`. I believe the relevant line is https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb#L35.

**Comment by buchgr** [comment]
Thanks! The installer that we use in the new formula does not ship with zsh completion. We'll need to fix that first. I opened an issue on bazelbuild

**Comment by soonho-tri** [comment]
@buchgr , thank you. Please feel free to close this one if you want.

**Comment by siddharthab** [comment]
Resolved by #22.
