### ISSUE TITLE
Homebrew bazel doesn't have embedded jdk

### ISSUE THREAD

**Issue by hsestupin** [bazelbuild/homebrew-tap#32]
I installed bazel from scratch via brew following the steps described here - https://blog.bazel.build/2018/08/22/bazel-homebrew.html

In our bazelrc file we don't have any `--javabase` or `--host_javabase` flags. But when I run `bazel build //... -s` I see the error `Unrecognized VM option 'CompactStrings'` - exactly like described in https://github.com/bazelbuild/bazel/issues/5726

When I'm trying to get the version of the embedded jdk by running:
```
/private/var/tmp/_bazel_{user_name}/e439d9fcbe1875cf9922b11e6b2acfbc/execroot/__main__/external/embedded_jdk/bin/java -version
```
I'm getting this:
```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```
This is my local jdk available through `which javac`.

But AFAIU embedded jdk should be jdk9 and it has to be included into the bazel distribution. But it seems that something went wrong. Some keys of `bazel info` are the following:
```
java-home: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre

release: release 0.20.0-homebrew
```

**Comment by kurtisnelson** [comment]
It seems tap pinning is not working, but when I used `brew install bazelbuild/tap/bazel` it fixed the problem.

**Comment by hsestupin** [comment]
That seems to be true. I've also figured out that `brew install bazelbuild/tap/bazel` works not so far ago.

**Comment by philwo** [comment]
I think tap pinning was just buggy in Homebrew and has been removed recently:

```
philwo@philwo-macbookpro2:~ $ brew tap-pin  
Error: Calling brew tap-pin user/tap is disabled! Use fully-scoped user/tap/formula naming instead.
```

We've updated the README.md accordingly, so hopefully this is no longer an issue. :)
