### ISSUE TITLE
How to downgrade / "brew install bazel@<version>" fails. 

### ISSUE THREAD

**Issue by drscotthawley** [bazelbuild/homebrew-tap#39]
Hi , thanks for preparing this.  I'm a bit stuck, and I'm wondering if the README could include information about not only how to upgrade, but also how to downgrade.
I landed here from Tensorflow issue https://github.com/tensorflow/tensorflow/issues/25490
in which downgrading bazel to 0.15.0 was suggested.  So...

$ brew install bazel@0.15.0
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
bazel ✔            ffmpeg ✔           apache-opennlp     conjure-up         crystal            mpd                ngircd             streamlink

Error: No available formula with the name "bazel@0.15.0" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

Let's see what versions are available. 

$ brew search bazel
==> Formulae
bazel ✔                                            bazelbuild/tap/bazel ✔                             bazelbuild/tap/ibazel

?  No version numbers listed? 

Ok, finally let's try `brew switch`:

$ brew switch bazel 0.15.0
Error: bazel does not have a version "0.15.0" in the Cellar.
bazel installed versions: 0.22.0

?  Would appreciate any help.

**Comment by cre8ivejp** [comment]
Same issue here.
There is any update on this?

**Comment by jamiesnape** [comment]
In general downgrading a homebrew formula is not supported. `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/bab70bd0f3bad4dbd755ec4e5357d8fd782f89d6/Formula/bazel.rb` may work (you would need to uninstall any other versions of `bazel` formulae first). You cannot add an arbitrary `@{version}` after a formula name, since each “version”  is actually a separate formulae that must be explicitly created. IIRC`brew switch` will only work if you previously installed that version and have not cleaned it up.

**Comment by SystemErrorWang** [comment]
@jamiesnape would you please tell me what should i do if i want to install bazel0.21.0? Failed to compose the correct url myself.

**Comment by jamiesnape** [comment]
Look at https://github.com/bazelbuild/homebrew-tap/commits/master/Formula/bazel.rb for the 0.21.0 release and you will see it was commit https://github.com/bazelbuild/homebrew-tap/commit/42a4bf1f4411084321e95f89c0653fe62f74ae10 on December 20th, 2018. 

Hence:

```brew install https://github.com/bazelbuild/homebrew-tap/blob/42a4bf1f4411084321e95f89c0653fe62f74ae10/Formula/bazel.rb```

**Comment by Imranmkt** [comment]
How to install bazel 0.24.1 on Mac ?  #jamiensnape

**Comment by jamiesnape** [comment]
Use the same process as the previous comment explains. I am afraid I cannot give instructions for reverting arbitrary versions of bazel.

@katre @philwo Can you close this issue? It is not this tap's problem at all.

**Comment by katre** [comment]
Closing this since it's not something Bazel's homebrew-tap can fix.

Thanks @jamiesnape for help answering.

**Comment by farazBhatti** [comment]
@Imranmkt  try:
`brew install https://github.com/bazelbuild/homebrew-tap/blob/b515f2b67ce6bc8c3c23e63de6235f130f868acf/Formula/bazel.rb`

**Comment by Imranmkt** [comment]
@farazBhatti Thank you for your comment. I tried the link to install bazel but it's showing unexpected syntax error.

Error: bazel: /Users/imran/Library/Caches/Homebrew/Formula/bazel.rb:7: syntax error, unexpected '<'
<!DOCTYPE html>

**Comment by plucury** [comment]
@Imranmkt Have try with `brew install https://raw.githubusercontent.com/bazelbuild/homebrew-tap/b515f2b67ce6bc8c3c23e63de6235f130f868acf/Formula/bazel.rb`

**Comment by farazBhatti** [comment]
@Imranmkt , i think a new thread should be opened for your problem so that other people facing problem  same as your's can also be benefited. we can discuss this issue on the new thread

**Comment by powderluv** [comment]
The URL has changed. I have been able to install .26.1 to build tensorflow 2.0 with
brew install https://raw.githubusercontent.com/bazelbuild/homebrew-tap/c8a0ccc2a8b442d9887d88c6380f835f533ffd47/Formula/bazel.rb

**Comment by envil** [comment]
To get install URL for your desired version, get the raw link of the bazel.rb, for example:
`https://raw.githubusercontent.com/bazelbuild/homebrew-tap/42a4bf1f4411084321e95f89c0653fe62f74ae10/Formula/bazel.rb`

then

`brew install https://raw.githubusercontent.com/bazelbuild/homebrew-tap/42a4bf1f4411084321e95f89c0653fe62f74ae10/Formula/bazel.rb`

**Comment by jvmncs** [comment]
a better solution to this problem:
```sh
brew tap bazelbuild/tap
brew extract bazel bazelbuild/tap --version X.X.X
```
